"""add vertical_tags to attendees

Revision ID: 4f68cbefaf01
Revises: b7607c8c95ba
Create Date: 2026-03-19 13:47:14.290343
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4f68cbefaf01'
down_revision: Union[str, None] = 'b7607c8c95ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendees', sa.Column('vertical_tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendees', 'vertical_tags')
    # ### end Alembic commands ###
