"""add privacy_mode to attendees

Revision ID: 6a28b2ff60c9
Revises: a1c9d5e72f33
Create Date: 2026-04-01 10:07:49.366183
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6a28b2ff60c9'
down_revision: Union[str, None] = 'a1c9d5e72f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendees', sa.Column('privacy_mode', sa.String(length=20), nullable=False, server_default='full'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendees', 'privacy_mode')
    # ### end Alembic commands ###
