"""add_photo_url_to_attendees

Revision ID: b7607c8c95ba
Revises: d4f6c7a1b2e0
Create Date: 2026-03-13 14:36:08.772382
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b7607c8c95ba'
down_revision: Union[str, None] = 'd4f6c7a1b2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendees', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.alter_column('attendees', 'crunchbase_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('attendees', 'pot_history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendees', 'pot_history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('attendees', 'crunchbase_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('attendees', 'photo_url')
    # ### end Alembic commands ###
